# .pre-commit-config.yaml
# https://pre-commit.com
# Enforces formatting, linting, typing, and doc hygiene for every commit.

repos:
  # Black: code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python{{ python_version }}

  # Ruff: ultra-fast linter and autofixer
  - repo: https://github.com/astral-sh/ruff
    rev: v0.4.5
    hooks:
      - id: ruff
        language_version: python{{ python_version }}

  # isort: import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python{{ python_version }}

  # mypy: type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        language_version: python{{ python_version }}

  # Pre-commit's own handy hooks (merge conflict, whitespace, file size)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json

  # Markdown linter (optional, but keeps docs clean)
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint

  # Jupyter notebook cleaner (strip execution counts, outputs)
  - repo: https://github.com/kynan/nbstripout
    rev: v0.6.1
    hooks:
      - id: nbstripout

  # YAML linter
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint

default_stages: [commit, push]
